version: "3"

services:
    postgresql-account:
        image: postgres:13
        
    postgresql-hotel:
        image: postgres:13

    postgresql-fly:
        image: postgres:13


    aggregator-company-api:
        build: 
            context: ./AggregatorCompany
            dockerfile: ./AggregatorCompany.Dockerfile
        image: aggregator-company-api

    account-company-api:
        build: 
            context: ./AccountCompany
            dockerfile: ./AccountCompany.Dockerfile
        image: account-company-api
        depends_on: 
            - postgresql-account  

    fly-company-api:
        build: 
            context: ./FlyCompany
            dockerfile: ./FlyCompany.Dockerfile
        image: fly-company-api
        depends_on: 
            - postgresql-fly

    hotel-company-api:
        build: 
            context: ./HotelCompany
            dockerfile: ./HotelCompany.Dockerfile
        image: hotel-company-api
        depends_on: 
            - postgresql-hotel