version: "3"

services:
    db:
        image: postgres:13
        container_name: 2pc-postgres
        volumes: 
            - ./Application/Application.DbScripts/init.sql :/docker-entrypoint-initdb.d/init.sql
        environment: 
            POSTGRES_DB: postgresdb
            POSTGRES_USER: superuser
            POSTGRES_PASSWORD: closeyoureyes

    api:
        build: 
            context: ./Application
            dockerfile: Dockerfile
        image: dot-net-core-api
        container_name: 2pc-api
        environment: 
            DB_HOST: db
            DB_DATABASE: postgresdb
            POSTGRES_USER: superuser
            DB_PASSWORD: closeyoureyes
        ports: 
            - 5002:80
        depends_on: 
            - db    

